### ISSUE TITLE
Add boot.rom to releases folder so game automatically downloads and will load on core launch

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/EpochGalaxy2_MiSTer#1]
Can you please add the game rom to the releases folder and rename to boot.rom?  This means that the downloader script will automatically download the file, and when the core is launched it will automatically load the core (I have tried this and it works).  This means people don't need to manually download the game file and then load it from the menu each time to play.  Will be a much more streamlined experience and should see more people trying out the core.

Also remember to keep your sys updated on your cores, this one is a couple of years behind ;-)

**Comment by pcornier** [comment]
Sys is not updated yet but I close it as the title was about boot.rom and not updating sys. I will try to take care of sys later.
